<?php
/**
 * NullCastle Systems — products-catalogue.php
 * Single source of truth for the product/service list.
 * Included by: product.php, products.php, recently-visited.php, most-visited.php
 *
 * Keys:
 *   id       – URL-safe slug (must match array key)
 *   num      – display number e.g. "001"
 *   color    – green | red | amber | cyan
 *   tag      – [label, css-class]
 *   name     – display name
 *   short    – one-line summary
 *   price    – starting price string
 *   period   – billing cadence string
 *   featured – (optional) bool, marks "Most Popular"
 *   img      – card / thumbnail image URL
 *   hero_img – large hero image URL (for product detail page)
 *   desc     – full paragraph description
 *   features – array of feature bullet strings
 *   cta      – call-to-action button label
 */

$PRODUCTS = [
  'threat-intel' => [
    'id'      => 'threat-intel',
    'num'     => '001',
    'color'   => 'red',
    'tag'     => ['LIVE DATA', 'tag-red'],
    'name'    => 'Threat Intelligence Platform',
    'short'   => 'Real-time dark-web & IOC intelligence pushed to your SIEM.',
    'price'   => '$4,200',
    'period'  => '/month',
    'img'     => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&q=85',
    'desc'    => 'Real-time ingestion of dark web forums, paste sites, C2 beacons and underground markets. Our TIP correlates 12M+ daily events into actionable, prioritised IOCs pushed directly to your SIEM. Think of it as having Raj living inside your network — minus the social anxiety.',
    'features'=> [
      'Dark web monitoring across 3,000+ forums & paste sites',
      'Custom threat actor tracking & adversary profiling',
      'STIX/TAXII 2.1 compatible automated feed',
      'CVE enrichment with exploit probability scoring',
      'Bi-weekly executive intelligence brief',
      'Slack/Teams/PagerDuty alert integration',
    ],
    'cta'     => 'Request Trial',
  ],
  'zero-trust' => [
    'id'      => 'zero-trust',
    'num'     => '002',
    'color'   => 'green',
    'tag'     => ['RECOMMENDED', 'tag-green'],
    'name'    => 'Zero-Trust Architecture',
    'short'   => 'Full-scope ZTA design, implementation & continuous validation.',
    'price'   => '$18K',
    'period'  => '+ retainer',
    'featured'=> true,
    'img'     => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=85',
    'desc'    => 'Full-scope ZTA design, implementation and continuous validation. We rip out implicit trust everywhere — network perimeter, identity, device, workload. We rebuild with micro-segmentation, continuous verification and least-privilege enforcement. Trust no one. Not even us.',
    'features'=> [
      'Identity-aware access proxy deployment',
      'Service mesh + mTLS full rollout',
      'Policy-as-code with automated drift detection',
      'CASB integration for SaaS applications',
      '30-day maturity re-assessment included',
      'Executive ZTA health dashboard',
    ],
    'cta'     => 'Start Assessment',
  ],
  'incident-response' => [
    'id'      => 'incident-response',
    'num'     => '003',
    'color'   => 'amber',
    'tag'     => ['24/7 SLA', 'tag-amber'],
    'name'    => 'Incident Response Retainer',
    'short'   => 'Sub-15-min acknowledgment. Sub-60-min engagement. Always.',
    'price'   => '$8,500',
    'period'  => '/month retainer',
    'img'     => 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1200&q=85',
    'desc'    => 'When the IR crew gets paged, the clock starts. Sub-15-minute acknowledgment, sub-60-minute engagement. We\'ve handled ransomware, supply-chain compromises, and one very awkward insider threat situation involving a VP and a USB drive. We don\'t judge. We contain.',
    'features'=> [
      '15-min acknowledgment / 60-min engagement SLA',
      'Dedicated IR commander assigned to your account',
      'Forensic image capture & chain-of-custody',
      'Legal-ready incident report & timeline',
      'Post-incident hardening recommendations',
      'Tabletop simulation exercises (quarterly)',
    ],
    'cta'     => 'Get Protected',
  ],
  'red-team' => [
    'id'      => 'red-team',
    'num'     => '004',
    'color'   => 'red',
    'tag'     => ['ADVERSARIAL', 'tag-red'],
    'name'    => 'Red Team Operations',
    'short'   => 'Full-scope cyber + physical adversary simulation.',
    'price'   => '$24K',
    'period'  => '/engagement',
    'img'     => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=85',
    'desc'    => 'Our operators attempt to break into your organisation using every technique a real adversary would — phishing, physical intrusion, zero-days, social engineering. We\'ve successfully breached banks, hospitals, and a particularly smug tech startup that had "unhackable" in their pitch deck.',
    'features'=> [
      'Full-scope red team (cyber + physical)',
      'Assumed breach simulation',
      'Social engineering & vishing campaigns',
      'Purple team collaborative debrief',
      'Custom threat actor emulation',
      'MITRE ATT&CK mapped kill-chain report',
    ],
    'cta'     => 'Book Engagement',
  ],
  'castlewall-os' => [
    'id'      => 'castlewall-os',
    'num'     => '005',
    'color'   => 'cyan',
    'tag'     => ['SOFTWARE', 'tag-cyan'],
    'name'    => 'CastleWall OS',
    'short'   => 'Hardened, zero-trust OS for high-assurance workloads.',
    'price'   => '$1,200',
    'period'  => '/node/year',
    'img'     => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=85',
    'desc'    => 'A hardened, zero-trust operating system for high-assurance workloads. Built on a verified microkernel, with mandatory access controls, post-quantum cryptography, and a read-only root filesystem. Ships with our NullCastle attestation service. Version 3.0 — Now GA.',
    'features'=> [
      'Verified microkernel (seL4-derived)',
      'Post-quantum TLS 1.4 stack',
      'TPM 3.0 remote attestation',
      'FIPS 140-3 certified crypto module',
      'Air-gap deployment supported',
      'Immutable, signed root filesystem',
    ],
    'cta'     => 'Download Trial',
  ],
  'vciso' => [
    'id'      => 'vciso',
    'num'     => '006',
    'color'   => 'amber',
    'tag'     => ['CONSULTING', 'tag-amber'],
    'name'    => 'vCISO Advisory',
    'short'   => 'Senior security executive embedded in your leadership team.',
    'price'   => '$6,500',
    'period'  => '/month',
    'img'     => 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&q=85',
    'desc'    => 'Not every company needs a full-time CISO. Every company needs someone who thinks like one. Our virtual CISO programme gives you a senior security executive embedded in your leadership team — board-level communication included, pranks not included.',
    'features'=> [
      'Dedicated vCISO with industry-specific experience',
      'Monthly board-level security briefings',
      'Regulatory compliance roadmap (SOC2, ISO27001, NIS2)',
      'Security hiring & programme build-out support',
      'Vendor security assessment reviews',
      'Risk register ownership & management',
    ],
    'cta'     => 'Start Conversation',
  ],
  'cloud-security' => [
    'id'      => 'cloud-security',
    'num'     => '007',
    'color'   => 'cyan',
    'tag'     => ['CLOUD', 'tag-cyan'],
    'name'    => 'Cloud Security Posture',
    'short'   => 'Continuous misconfiguration detection across AWS, Azure & GCP.',
    'price'   => '$3,800',
    'period'  => '/month',
    'img'     => 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&q=85',
    'desc'    => 'The cloud is not someone else\'s security problem. Our CSPM service continuously scans your AWS, Azure, and GCP environments for misconfigurations, exposed secrets, overprivileged identities, and compliance drift — and auto-remediates where you allow it.',
    'features'=> [
      'Agentless multi-cloud scanning (AWS / Azure / GCP)',
      'IaC security scanning (Terraform, CloudFormation)',
      'Secrets detection in repos and runtime',
      'Identity & access entitlement analysis',
      'Auto-remediation playbooks',
      'CIS Benchmarks & NIST 800-53 mapping',
    ],
    'cta'     => 'Get Cloud Coverage',
  ],
  'pentest' => [
    'id'      => 'pentest',
    'num'     => '008',
    'color'   => 'green',
    'tag'     => ['OFFENSIVE', 'tag-green'],
    'name'    => 'Penetration Testing',
    'short'   => 'CREST-certified web, API, mobile and infrastructure pentesting.',
    'price'   => '$12K',
    'period'  => '/engagement',
    'img'     => 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=1200&q=85',
    'desc'    => 'CREST-certified penetration testing across web applications, APIs, mobile apps, internal networks, and external perimeters. Every test is scoped, methodical, and produces a report that your dev team will actually read — because we write it in plain language.',
    'features'=> [
      'Web application & API (OWASP Top 10+)',
      'Internal & external network infrastructure',
      'Mobile applications (iOS & Android)',
      'Cloud environment configuration review',
      'Plain-language executive & technical report',
      'Free retest within 90 days of remediation',
    ],
    'cta'     => 'Book a Pentest',
  ],
  'soc-as-service' => [
    'id'      => 'soc-as-service',
    'num'     => '009',
    'color'   => 'green',
    'tag'     => ['MANAGED', 'tag-green'],
    'name'    => 'SOC-as-a-Service',
    'short'   => '24/7 managed detection & response with human-led triage.',
    'price'   => '$11,000',
    'period'  => '/month',
    'img'     => 'https://images.unsplash.com/photo-1551808525-51a94da548ce?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1551808525-51a94da548ce?w=1200&q=85',
    'desc'    => 'Around-the-clock threat monitoring, detection, and response backed by human analysts — not just alert pipelines. Our SOC ingests your logs, EDR telemetry, cloud events, and network flows and turns noise into prioritised, actioned alerts with full context.',
    'features'=> [
      '24/7/365 human-led alert triage',
      'SIEM ingestion (Splunk, Sentinel, Chronicle)',
      'EDR integration (CrowdStrike, SentinelOne, Defender)',
      'MTTR < 4 hours for critical alerts',
      'Monthly threat landscape report',
      'Dedicated SOC Tier-2 analyst assigned',
    ],
    'cta'     => 'Activate SOC',
  ],
  'compliance' => [
    'id'      => 'compliance',
    'num'     => '010',
    'color'   => 'amber',
    'tag'     => ['COMPLIANCE', 'tag-amber'],
    'name'    => 'Compliance Accelerator',
    'short'   => 'SOC 2, ISO 27001, NIS2 & DORA — evidence-ready in weeks.',
    'price'   => '$9,000',
    'period'  => '/engagement',
    'img'     => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    'hero_img'=> 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=85',
    'desc'    => 'Compliance doesn\'t have to take 18 months and cost a fortune. Our Compliance Accelerator gets you audit-ready for SOC 2 Type II, ISO 27001, NIS2, DORA, and more using automated evidence collection, pre-built control libraries, and an auditor who has seen it all.',
    'features'=> [
      'Gap assessment against target framework',
      'Pre-built control library & policy templates',
      'Automated evidence collection tooling',
      'Dedicated compliance project manager',
      'Mock audit + auditor introductions',
      'Ongoing compliance monitoring post-certification',
    ],
    'cta'     => 'Start Compliance Journey',
  ],
];
